import {Router,json} from 'express';
import {randomBytes,createHash,createCipheriv,createDecipheriv,randomUUID} from 'node:crypto';
import {z} from 'zod';
import {profileSchema} from './schema.mjs';
import {savedReportSchema} from './saved-report.mjs';
import {isAllowedOrigin} from './origins.mjs';
export function googleProfilePhoto(user){
 const providers=user?.app_metadata?.providers||[];
 if(user?.app_metadata?.provider!=='google'&&!providers.includes('google')&&!user?.identities?.some(identity=>identity.provider==='google'))return null;
 const value=user?.user_metadata?.avatar_url||user?.user_metadata?.picture;
 if(typeof value!=='string')return null;
 try{const url=new URL(value);return url.protocol==='https:'&&(url.hostname==='googleusercontent.com'||url.hostname.endsWith('.googleusercontent.com'))?url.toString():null;}catch{return null;}
}
export function authRouter(env=process.env){
 const router=Router();const base=(env.SUPABASE_URL||'').replace(/\/$/,'');const apiKey=env.SUPABASE_PUBLISHABLE_KEY||env.SUPABASE_ANON_KEY||'';const appUrl=(env.APP_URL||'http://localhost:5187').replace(/\/$/,'');const apiPublicUrl=(env.API_PUBLIC_URL||appUrl).replace(/\/$/,'');const enabled=!!(base&&apiKey&&env.SESSION_SECRET?.length>=32);const secure=appUrl.startsWith('https://');
 const key=createHash('sha256').update(env.SESSION_SECRET||'unconfigured').digest();
 const seal=v=>{const iv=randomBytes(12);const cipher=createCipheriv('aes-256-gcm',key,iv);const data=Buffer.concat([cipher.update(JSON.stringify(v)),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),data]).toString('base64url');};
 const unseal=value=>{try{const b=Buffer.from(value,'base64url');const d=createDecipheriv('aes-256-gcm',key,b.subarray(0,12));d.setAuthTag(b.subarray(12,28));return JSON.parse(Buffer.concat([d.update(b.subarray(28)),d.final()]).toString());}catch{return null;}};
 const read=(req,name)=>unseal((name==='yoeo_session'&&req.get('x-yoeo-session'))||(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith(name+'='))?.slice(name.length+1)||'');
 const cookie=(res,name,value,seconds)=>{const encoded=value?seal(value):'';res.append('Set-Cookie',`${name}=${encoded}; Path=/api; HttpOnly; SameSite=Lax; Max-Age=${seconds}${secure?'; Secure':''}`);return encoded;};
 const route=fn=>async(req,res)=>{try{await fn(req,res);}catch(e){res.status(e.status||502).json({error:e.publicMessage||'Account service unavailable. Please try again.'});}};
 const fail=(status,message)=>{throw Object.assign(new Error(message),{status,publicMessage:message});};
 async function request(path,{method='GET',body,token}={}){const r=await fetch(`${base}${path}`,{method,headers:{apikey:apiKey,'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(15000)});if(!r.ok)fail(r.status===429?429:400,r.status===429?'Too many attempts. Please wait before trying again.':'The account request could not be completed. Check your details and account configuration.');const text=await r.text();return text?JSON.parse(text):null;}
 function saveSession(res,s){if(!s.access_token||!s.refresh_token)fail(401,'Sign-in did not complete.');const sessionData={access:s.access_token,refresh:s.refresh_token,expires:Date.now()+(s.expires_in||3600)*1000};return {sessionData,sessionToken:cookie(res,'yoeo_session',sessionData,2592000)};}
 async function session(req,res){let s=read(req,'yoeo_session');if(!s)fail(401,'Please sign in first.');if(s.expires<Date.now()+60000){const refreshed=await request('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:s.refresh}});s=saveSession(res,refreshed).sessionData;}const user=await request('/auth/v1/user',{token:s.access});return {user,token:s.access,sessionToken:seal(s)};}
 router.get('/auth/config',(_req,res)=>res.json({enabled,providers:{google:enabled&&env.AUTH_GOOGLE_ENABLED==='true',apple:enabled&&env.AUTH_APPLE_ENABLED==='true'}}));
 const buckets=new Map();
 router.use((req,res,next)=>{if(!enabled)return res.status(503).json({error:'Cloud accounts are not configured yet. Your local profile still works.'});const origin=req.get('origin');if(!isAllowedOrigin(origin,env,appUrl))return res.status(403).json({error:'Origin not allowed.'});if(req.method!=='GET'&&!req.is('application/json'))return res.status(415).json({error:'JSON required.'});if(req.path.startsWith('/auth/')&&req.method==='POST'){const now=Date.now();for(const[k,v]of buckets)if(now-v.start>900000)buckets.delete(k);const b=buckets.get(req.ip)||{start:now,count:0};b.count++;buckets.set(req.ip,b);if(b.count>15)return res.status(429).json({error:'Too many attempts. Try again later.'});}next();});
 router.use(json({limit:'256kb'}));
 router.get('/auth/session',route(async(req,res)=>{const {user,sessionToken}=await session(req,res);res.json({user:{id:user.id,email:user.email,avatarUrl:googleProfilePhoto(user)},sessionToken});}));
 router.get('/auth/oauth/:provider',route(async(req,res)=>{const p=req.params.provider;if(!['google','apple'].includes(p)||env[`AUTH_${p.toUpperCase()}_ENABLED`]!=='true')fail(400,'This sign-in provider is not enabled.');const verifier=randomBytes(32).toString('base64url');const flow={verifier,expires:Date.now()+600000};const browserFlow=req.query.mode==='json'||req.query.mode==='native';const nativeFlow=req.query.mode==='native';if(!browserFlow)cookie(res,'yoeo_pkce',flow,600);const url=new URL(base+'/auth/v1/authorize');url.search=new URLSearchParams({provider:p,redirect_to:nativeFlow?apiPublicUrl+'/api/auth/native-callback':browserFlow?appUrl+'/?account=1&oauth=1':appUrl+'/api/auth/callback',code_challenge:createHash('sha256').update(verifier).digest('base64url'),code_challenge_method:'s256'}).toString();if(browserFlow)return res.json({url:url.toString(),flowToken:seal(flow)});res.redirect(url.toString());}));
 router.get('/auth/native-callback',(req,res)=>{const target=new URL('app.yoeo.mobile://auth/callback');for(const key of ['code','error','error_description']){if(typeof req.query[key]==='string')target.searchParams.set(key,req.query[key]);}res.set('Referrer-Policy','no-referrer');res.redirect(302,target.toString());});
 router.get('/auth/callback',route(async(req,res)=>{const flow=read(req,'yoeo_pkce');cookie(res,'yoeo_pkce',null,0);if(!flow||flow.expires<Date.now()||typeof req.query.code!=='string')fail(401,'Sign-in expired. Please start again.');const s=await request('/auth/v1/token?grant_type=pkce',{method:'POST',body:{auth_code:req.query.code,code_verifier:flow.verifier}});const {sessionToken}=saveSession(res,s);res.redirect(appUrl+'/?account=1#session='+encodeURIComponent(sessionToken));}));
 router.post('/auth/oauth/callback',route(async(req,res)=>{const input=z.object({code:z.string().min(8).max(4096),flowToken:z.string().min(20).max(4096)}).parse(req.body);const flow=unseal(input.flowToken);if(!flow||flow.expires<Date.now())fail(401,'Sign-in expired. Please start again.');const s=await request('/auth/v1/token?grant_type=pkce',{method:'POST',body:{auth_code:input.code,code_verifier:flow.verifier}});const {sessionToken}=saveSession(res,s);res.json({ok:true,sessionToken});}));
 router.post('/auth/email',route(async(req,res)=>{const email=z.email().parse(req.body.email);await request('/auth/v1/otp',{method:'POST',body:{email,create_user:true}});res.json({message:'If sign-in is available, a code has been sent. Check your inbox.'});}));
 router.post('/auth/verify',route(async(req,res)=>{const input=z.object({email:z.email(),code:z.string().regex(/^\d{6,8}$/)}).parse(req.body);const s=await request('/auth/v1/verify',{method:'POST',body:{email:input.email,token:input.code,type:'email'}});const {sessionToken}=saveSession(res,s);res.json({ok:true,sessionToken});}));
 router.post('/auth/signup',route(async(req,res)=>{const input=z.object({email:z.email(),password:z.string().min(12).max(128)}).parse(req.body);const s=await request('/auth/v1/signup',{method:'POST',body:input});if(!s?.access_token||!s?.refresh_token)return res.json({ok:true,needsConfirmation:true,message:'Check your email to confirm your account, then sign in.'});const {sessionToken}=saveSession(res,s);res.json({ok:true,sessionToken,user:{id:s.user?.id,email:s.user?.email}});}));
 router.post('/auth/login',route(async(req,res)=>{const input=z.object({email:z.email(),password:z.string().min(1).max(128)}).parse(req.body);const s=await request('/auth/v1/token?grant_type=password',{method:'POST',body:input});const {sessionToken}=saveSession(res,s);res.json({ok:true,sessionToken,user:{id:s.user?.id,email:s.user?.email}});}));
 router.post('/auth/logout',route(async(req,res)=>{const s=read(req,'yoeo_session');cookie(res,'yoeo_session',null,0);if(s)await request('/auth/v1/logout',{method:'POST',token:s.access});res.json({ok:true});}));
 router.get('/account/profiles',route(async(req,res)=>{const {token,user}=await session(req,res);res.json(await request(`/rest/v1/person_profiles?owner_id=eq.${user.id}&select=id,name,allergens,avatar,completed&order=created_at.asc`,{token}));}));
 router.post('/account/profiles',route(async(req,res)=>{const {token,user}=await session(req,res);const p=z.object({id:z.uuid().optional(),name:z.string().trim().min(1).max(40),avatar:z.string().max(150000).regex(/^data:image\/jpeg;base64,[A-Za-z0-9+/]+=*$/).nullable().optional(),allergens:profileSchema,completed:z.boolean()}).parse(req.body);const id=p.id||randomUUID();if(p.id){const existing=await request(`/rest/v1/person_profiles?id=eq.${id}&owner_id=eq.${user.id}&select=id`,{token});if(!existing.length)fail(404,"Profile not found in this account.");}await request(`/rest/v1/person_profiles${p.id?`?id=eq.${id}&owner_id=eq.${user.id}`:''}`,{method:p.id?'PATCH':'POST',token,body:{...p,id,owner_id:user.id}});res.json({id});}));
 router.delete('/account/profiles/:id',route(async(req,res)=>{const {token,user}=await session(req,res);const id=z.uuid().parse(req.params.id);await request(`/rest/v1/person_profiles?id=eq.${id}&owner_id=eq.${user.id}`,{method:'DELETE',token});res.json({ok:true});}));
 // Saved scan results are an optional account feature: they hold menu text and findings, never photos or payment data.
 router.get('/account/reports',route(async(req,res)=>{const {token,user}=await session(req,res);const rows=await request(`/rest/v1/saved_reports?owner_id=eq.${user.id}&select=report&order=created_at.desc&limit=50`,{token});res.json((rows||[]).map(row=>row.report));}));
 router.post('/account/reports',route(async(req,res)=>{const {token,user}=await session(req,res);const parsed=savedReportSchema.safeParse(req.body);if(!parsed.success||JSON.stringify(parsed.data).length>200000)fail(400,'This result cannot be synced.');const report=parsed.data;const existing=await request(`/rest/v1/saved_reports?id=eq.${report.id}&owner_id=eq.${user.id}&select=id`,{token});await request(existing?.length?`/rest/v1/saved_reports?id=eq.${report.id}&owner_id=eq.${user.id}`:'/rest/v1/saved_reports',{method:existing?.length?'PATCH':'POST',token,body:existing?.length?{report}:{id:report.id,owner_id:user.id,report,created_at:report.createdAt}});res.json({id:report.id});}));
 router.delete('/account/reports/:id',route(async(req,res)=>{const {token,user}=await session(req,res);const id=z.uuid().parse(req.params.id);await request(`/rest/v1/saved_reports?id=eq.${id}&owner_id=eq.${user.id}`,{method:'DELETE',token});res.json({ok:true});}));
 router.post('/auth/password',route(async(req,res)=>{const {token}=await session(req,res);const password=z.string().min(12).max(128).parse(req.body.password);await request('/auth/v1/user',{method:'PUT',token,body:{password}});res.json({ok:true});}));
 router.delete('/account',route(async(req,res)=>{const {token}=await session(req,res);if(req.body.confirm!=='DELETE')fail(400,'Confirm account deletion.');await request('/rest/v1/rpc/delete_own_account',{method:'POST',token,body:{}});cookie(res,'yoeo_session',null,0);res.json({ok:true});}));
 router.getSession = session;
 router.accountsEnabled = enabled;
 return router;
}

