import {createRequire} from 'node:module';
import path from 'node:path';
import assert from 'node:assert/strict';
const {chromium}=createRequire(path.resolve(process.env.YOEO_TOOLS_DIR,'.','package.json'))('playwright');
const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:360,height:712}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5187');await page.getByRole('button',{name:'Get started',exact:true}).click();
for(const severity of ['Critical','Avoid','Safe']){await page.getByRole('button',{name:severity,exact:true}).click();assert.match(await page.locator('.mascot-panel > img').getAttribute('src'),new RegExp('imgSizeLgSeverity'+severity+'CategoryMilk'));assert.notEqual(await page.locator('.mascot-panel > img').evaluate(e=>getComputedStyle(e).animationName),'none');}
await page.screenshot({path:'test-results/onboarding-safe.png'});
await page.getByRole('button',{name:'Next',exact:true}).click();await page.getByRole('button',{name:'Avoid',exact:true}).click();await page.getByRole('button',{name:'Previous category'}).click();assert.equal(await page.getByRole('button',{name:'Safe',exact:true}).getAttribute('aria-pressed'),'true');await page.getByRole('button',{name:'Next',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Avoid',exact:true}).getAttribute('aria-pressed'),'true');
await page.emulateMedia({reducedMotion:'reduce'});await page.getByRole('button',{name:'Critical',exact:true}).click();assert.equal(await page.locator('.mascot-panel > img').evaluate(e=>getComputedStyle(e).animationName),'none');
for(let i=1;i<8;i++){await page.getByRole('button',{name:'Safe',exact:true}).click();await page.getByRole('button',{name:'Next',exact:true}).click();}await page.getByLabel('Your name').fill('Sam');await page.getByRole('button',{name:'Let’s go',exact:true}).click();await page.getByRole('heading',{name:'Welcome to YOEO!'}).waitFor();await page.getByRole('button',{name:'Start Analyzing'}).waitFor();
await page.getByRole('navigation').getByRole('button',{name:'Profile',exact:true}).click();await page.getByRole('button',{name:'Edit Profile',exact:true}).click();await page.getByLabel('Name',{exact:true}).fill('Sammy');await page.getByLabel('Upload profile photo').setInputFiles('public/assets/183-2448-imgImage42.png');await page.getByRole('button',{name:'Use generic avatar'}).waitFor();await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('heading',{name:'Sammy',exact:true}).waitFor();await page.screenshot({path:'test-results/profile-updated.png'});
await page.getByRole('button',{name:'Edit Profile',exact:true}).click();await page.getByRole('button',{name:'Reset password',exact:true}).click();await page.getByLabel('New password',{exact:true}).fill('test-password-123');await page.getByLabel('Confirm new password').fill('different-password');await page.getByRole('button',{name:'Reset password',exact:true}).click();await page.getByText('Passwords do not match.',{exact:true}).waitFor();await page.getByRole('button',{name:'Go back',exact:true}).click();await page.getByRole('button',{name:'Delete local profile and results',exact:true}).click();await page.getByRole('button',{name:'Keep my data',exact:true}).click();await page.getByRole('button',{name:'Go back',exact:true}).click();await page.getByRole('button',{name:'Subscription',exact:true}).click();await page.getByRole('tab',{name:'Monthly'}).click();await page.getByRole('tab',{name:'Yearly'}).click();await page.screenshot({path:'test-results/subscription.png'});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);assert.deepEqual(await page.locator('img').evaluateAll(imgs=>imgs.filter(i=>!i.complete||!i.naturalWidth).map(i=>i.src)),[]);await browser.close();console.log('Profile checks passed: original severity art, animations, reduced motion, back navigation, welcome confirmation, avatar upload, name editing, reset validation, deletion cancellation and subscription tabs.');
