import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type AppLanguage = 'en' | 'de' | 'zh-CN';
export type LanguagePreference = 'system' | AppLanguage;
const STORAGE_KEY = 'yoeo-language';

const de: Record<string, string> = {
  'Please wait for your account to load.':'Bitte warte, bis dein Konto geladen ist.','This permanently deletes your YOEO account and its app database records, then removes your local YOEO profile and saved results from this device.':'Dadurch werden dein YOEO-Konto und die zugehörigen App-Datenbankeinträge dauerhaft gelöscht. Anschließend werden dein lokales YOEO-Profil und deine gespeicherten Ergebnisse von diesem Gerät entfernt.','Your YOEO account and app data on this device have been deleted. Your store subscription was not canceled.':'Dein YOEO-Konto und die App-Daten auf diesem Gerät wurden gelöscht. Dein Store-Abonnement wurde nicht gekündigt.',
  'Unlimited scans':'Unbegrenzte Scans','Find an allergen':'Allergen suchen','Type an allergen name':'Allergen eingeben','No matching allergens.':'Keine passenden Allergene.','No allergens in your profile yet.':'Noch keine Allergene im Profil.','Change profile photo':'Profilfoto ändern','Profile photo updated':'Profilfoto aktualisiert','Profile photo removed':'Profilfoto entfernt','Remove photo':'Foto entfernen','Manage or cancel subscription':'Abo verwalten oder kündigen','Deleting your YOEO account does not cancel a subscription. Manage it through the store account used to purchase it.':'Das Löschen deines YOEO-Kontos kündigt kein Abo. Verwalte es im Store-Konto, mit dem es gekauft wurde.',
  Guest:'Gast','Hi there,':'Hallo,',Settings:'Einstellungen',Account:'Konto',
  'Uploading photos…':'Fotos werden hochgeladen…', 'Waiting for analysis…':'Analyse wird vorbereitet…',
  'Sending your photos securely.':'Deine Fotos werden sicher übertragen.',
  'Photos uploaded. Waiting for the server to finish checking the menu.':'Fotos hochgeladen. Wir warten, bis der Server die Speisekarte geprüft hat.',
  'Photo upload':'Foto-Upload', '{seconds}s elapsed':'{seconds} s vergangen',
  'Larger menus can take longer. You can cancel and retry with fewer photos.':'Große Speisekarten können länger dauern. Du kannst abbrechen und es mit weniger Fotos erneut versuchen.',
  Back:'Zurück', 'Return to previous screen':'Zur vorherigen Seite zurückkehren',
  'Unlock YOEO Pro':'YOEO Pro freischalten',
  'Save results and revisit them anytime with YOEO Pro.':'Speichere Ergebnisse mit YOEO Pro und sieh sie dir jederzeit wieder an.',
  'You’ve used your three free scans. Get YOEO Pro to keep analyzing.':'Deine drei kostenlosen Scans sind aufgebraucht. Mit YOEO Pro kannst du weiter analysieren.',
  'Unlimited analyses and saved results, all in one plan.':'Unbegrenzte Analysen und gespeicherte Ergebnisse in einem Abo.',
  'Sign up or sign in to upgrade':'Zum Upgrade registrieren oder anmelden',
  'Checking subscription…':'Abo wird geprüft…',

  'Eat safely everyday':'Jeden Tag sicher essen','Get started':'Loslegen','What are you allergic to?':'Wogegen bist du allergisch?',
  'Choose the severity for each category':'Wähle die Einstufung für jede Kategorie','Previous category':'Vorherige Kategorie','Category {current} of {total}':'Kategorie {current} von {total}','Not selected yet':'Noch nicht ausgewählt',
  Critical:'Kritisch',Avoid:'Vermeiden',Safe:'Sicher',Uncertain:'Unsicher',Untracked:'Nicht erfasst',Next:'Weiter','What’s your name?':'Wie heißt du?','Almost there — just one last step':'Fast geschafft – nur noch ein Schritt','Your name':'Dein Name','Let’s go':'Los geht’s',
  'Welcome to YOEO!':'Willkommen bei YOEO!','Get ready to eat safely everyday':'Mach dich bereit, jeden Tag sicher zu essen','Continue to home':'Zur Startseite','Hi {name},':'Hallo {name},','Ready to eat safely?':'Bereit, sicher zu essen?','My Allergens':'Meine Allergene',
  'Edit allergens':'Allergene bearbeiten','Export allergen profile':'Allergenprofil exportieren','No allergens marked to avoid.':'Keine zu vermeidenden Allergene markiert.','Review your allergen profile':'Allergenprofil prüfen','Start Analyzing':'Analyse starten','Add allergen':'Allergen hinzufügen',
  'No allergens in {severity}.':'Keine Allergene unter „{severity}“.','Add an allergen to personalize your checks.':'Füge ein Allergen hinzu, um deine Prüfungen anzupassen.','“Safe” records your own tolerance. It does not verify that a dish is safe to eat.':'„Sicher“ dokumentiert deine eigene Verträglichkeit. Es bestätigt nicht, dass ein Gericht sicher ist.',
  Home:'Start',Allergens:'Allergene',Profile:'Profil','Main navigation':'Hauptnavigation','Saved Results':'Gespeicherte Ergebnisse',Subscription:'Abonnement','Edit Profile':'Profil bearbeiten','Data Sources':'Datenquellen','Data Resources':'Datenquellen','App Settings':'App-Einstellungen','Manage your preferences and local data.':'Verwalte deine Einstellungen und lokalen Daten.','Sign in or create account':'Anmelden oder Konto erstellen','Install YOEO on this phone':'YOEO auf diesem Telefon installieren','Sign out':'Abmelden',
  Local:'Lokal',Free:'Kostenlos',Pro:'Pro','Pro scans active':'Pro-Scans aktiv','{remaining} of 3 free scans remaining':'{remaining} von 3 kostenlosen Scans übrig','{count} saved analysis on this device':'{count} gespeicherte Analyse auf diesem Gerät','{count} saved analyses on this device':'{count} gespeicherte Analysen auf diesem Gerät',
  Language:'Sprache','System default':'Systemstandard',English:'Englisch',German:'Deutsch','Simplified Chinese':'Vereinfachtes Chinesisch','Install on your phone':'Auf deinem Telefon installieren','Open your browser’s menu and choose “Add to Home Screen” or “Install app.”':'Öffne das Browsermenü und wähle „Zum Startbildschirm“ oder „App installieren“.','Your data':'Deine Daten','Export my data':'Meine Daten exportieren',
  'Does this menu have an allergen list?':'Hat diese Speisekarte eine Allergenliste?','Usually on the last page, marked with letter codes':'Meist auf der letzten Seite und mit Buchstabencodes markiert','Yes, upload the list':'Ja, Liste hochladen','No, upload the menu':'Nein, Speisekarte hochladen','Yes, take the list':'Ja, Liste fotografieren','No, take the menu':'Nein, Speisekarte fotografieren','Take the allergen list':'Allergenliste fotografieren','Take the menu':'Speisekarte fotografieren','Review the allergen list':'Allergenliste prüfen','Review the menu':'Speisekarte prüfen',
  'Fit the {kind} inside the frame':'{kind} in den Rahmen einpassen',menu:'Speisekarte','allergen list':'Allergenliste','Choose a photo':'Foto auswählen','Take photo':'Foto aufnehmen','Open device camera':'Gerätekamera öffnen',Gallery:'Galerie','Device camera':'Gerätekamera',Device:'Geräte-',camera:'kamera','Add a menu photo':'Foto der Speisekarte hinzufügen','Allergen list':'Allergenliste',Menu:'Speisekarte',Food:'Lebensmittel',Add:'Hinzufügen',photo:'Foto','Continue to the menu':'Weiter zur Speisekarte',
  'I agree to send these photos and my allergen preferences to YOEO’s server and {provider} for this analysis. AI can make mistakes; confirm ingredients and cross-contact with staff.':'Ich stimme zu, diese Fotos und meine Allergeneinstellungen für diese Analyse an den YOEO-Server und {provider} zu senden. KI kann Fehler machen; bestätige Zutaten und Kreuzkontakt beim Personal.',
  'Analysis needs your attention':'Analyse erfordert deine Aufmerksamkeit','Upgrade to Pro':'Auf Pro upgraden','Sign in to continue':'Anmelden, um fortzufahren','Preparing photos…':'Fotos werden vorbereitet…','Analyze {count} photo':'{count} Foto analysieren','Analyze {count} photos':'{count} Fotos analysieren','Retake this photo':'Foto erneut aufnehmen','Analyzing your results':'Ergebnisse werden analysiert','Analyzing your results…':'Ergebnisse werden analysiert…','Reading the menu and checking your allergens.':'Speisekarte wird gelesen und auf deine Allergene geprüft.',Cancel:'Abbrechen','Discard this scan?':'Diesen Scan verwerfen?','Your photos won’t be saved.':'Deine Fotos werden nicht gespeichert.',Discard:'Verwerfen',Continue:'Fortfahren',
  Milk:'Milch',Eggs:'Eier','Cereals containing gluten':'Glutenhaltiges Getreide','Peanuts & Tree Nuts':'Erdnüsse & Schalenfrüchte','Fish, Crustaceans & Molluscs':'Fisch, Krebstiere & Weichtiere','Soybeans, Lupin & Sesame':'Sojabohnen, Lupinen & Sesam','Celery & Mustard':'Sellerie & Senf',Sulphites:'Sulfite',
  All:'Alle','Allergen Check':'Allergenprüfung','Select what to show':'Auswahl der Ergebnisse','Show all results':'Alle Ergebnisse anzeigen','Check all {count} dishes at once':'Alle {count} Gerichte gleichzeitig prüfen','Or select specific dishes':'Oder einzelne Gerichte auswählen','Check {count} dishes':'{count} Gerichte prüfen','Allergens found':'Gefundene Allergene','No allergens were identified. Safety is still unconfirmed.':'Es wurden keine Allergene erkannt. Die Sicherheit ist noch nicht bestätigt.','From allergen list':'Aus der Allergenliste','Declared on menu':'Auf der Speisekarte angegeben','AI estimate':'KI-Einschätzung','No allergens identified':'Keine Allergene erkannt','Safety is unconfirmed':'Sicherheit nicht bestätigt','Evidence & questions':'Nachweise & Fragen','Visible / listed ingredients:':'Sichtbare / aufgeführte Zutaten:',Declared:'Angegeben',Possible:'Möglich','What we couldn’t confirm':'Was nicht bestätigt werden konnte','Ask the restaurant':'Im Restaurant nachfragen','No dishes in this category.':'Keine Gerichte in dieser Kategorie.','Confirm before you eat':'Vor dem Essen bestätigen','Read the allergen list':'Allergenliste lesen','Read the menu':'Speisekarte lesen','No additional menu text was extracted.':'Es wurde kein weiterer Speisekartentext erkannt.','Download structured report (JSON)':'Strukturierten Bericht herunterladen (JSON)','Analysis from {date}. Based on your allergen profile at that time.':'Analyse vom {date}. Basierend auf deinem damaligen Allergenprofil.','Results saved on this device':'Ergebnisse auf diesem Gerät gespeichert','Save results':'Ergebnisse speichern','Back to home':'Zur Startseite','Filter saved results':'Gespeicherte Ergebnisse filtern','Delete {title}':'{title} löschen','No tracked allergens detected':'Keine erfassten Allergene erkannt','Confirm ingredients before eating':'Zutaten vor dem Essen bestätigen','No matching results':'Keine passenden Ergebnisse','Your results, in one place':'Deine Ergebnisse an einem Ort','Choose another filter to see your saved analyses.':'Wähle einen anderen Filter, um gespeicherte Analysen zu sehen.','Save an analysis to come back to it here.':'Speichere eine Analyse, um sie später hier wiederzufinden.','Analyze a menu':'Speisekarte analysieren','Go back':'Zurück','Close':'Schließen','Profile photo':'Profilfoto','Open profile':'Profil öffnen',
  'View and change profile photo':'Profilfoto ansehen und ändern','Profile saved':'Profil gespeichert',Name:'Name','Email address':'E-Mail-Adresse','Sign in to connect your email':'Anmelden, um deine E-Mail zu verbinden','Reset password':'Passwort zurücksetzen',Save:'Speichern','Delete account':'Konto löschen','Delete local profile and results':'Lokales Profil und Ergebnisse löschen','Clear local data':'Lokale Daten löschen','Delete data':'Daten löschen','Delete data?':'Daten löschen?','Deleting…':'Wird gelöscht…','Deleting your data…':'Deine Daten werden gelöscht…','Deleting your account and associated data. This usually takes a few seconds.':'Dein Konto und die zugehörigen Daten werden gelöscht. Dies dauert normalerweise nur wenige Sekunden.','Removing your data from this device. This usually takes a few seconds.':'Deine Daten werden von diesem Gerät entfernt. Dies dauert normalerweise nur wenige Sekunden.','Your data has been deleted':'Deine Daten wurden gelöscht','Your account, associated database data, and all data stored by this app on this device have been deleted.':'Dein Konto, die zugehörigen Datenbankdaten und alle von dieser App auf diesem Gerät gespeicherten Daten wurden gelöscht.','All data stored by this app on this device has been deleted.':'Alle von dieser App auf diesem Gerät gespeicherten Daten wurden gelöscht.','Keep my data':'Meine Daten behalten','Close profile photo':'Profilfoto schließen','Choose image source':'Bildquelle auswählen',Camera:'Kamera',Photo:'Foto','Close allergen details':'Allergendetails schließen','Move to {severity}':'Zu „{severity}“ verschieben','Remove from profile':'Aus dem Profil entfernen',Allergen:'Allergen',Severity:'Einstufung','Save allergen':'Allergen speichern',
};

const zh: Record<string, string> = {
  'Please wait for your account to load.':'请等待账户加载完成。','This permanently deletes your YOEO account and its app database records, then removes your local YOEO profile and saved results from this device.':'这将永久删除你的 YOEO 账户及其应用数据库记录，然后从此设备移除本地 YOEO 档案和已保存的结果。','Your YOEO account and app data on this device have been deleted. Your store subscription was not canceled.':'你的 YOEO 账户及此设备上的应用数据已删除。应用商店订阅并未取消。',
  'Unlimited scans':'无限次扫描','Find an allergen':'查找过敏原','Type an allergen name':'输入过敏原名称','No matching allergens.':'没有匹配的过敏原。','No allergens in your profile yet.':'档案中还没有过敏原。','Change profile photo':'更换头像','Profile photo updated':'头像已更新','Profile photo removed':'头像已移除','Remove photo':'移除照片','Manage or cancel subscription':'管理或取消订阅','Deleting your YOEO account does not cancel a subscription. Manage it through the store account used to purchase it.':'删除 YOEO 账户不会取消订阅。请在购买时使用的应用商店账户中管理订阅。',
  Guest:'访客','Hi there,':'你好，',Settings:'设置',Account:'账户',
  'Uploading photos…':'正在上传照片…', 'Waiting for analysis…':'正在等待分析…',
  'Sending your photos securely.':'正在安全传输照片。',
  'Photos uploaded. Waiting for the server to finish checking the menu.':'照片已上传。正在等待服务器完成菜单分析。',
  'Photo upload':'照片上传', '{seconds}s elapsed':'已用时 {seconds} 秒',
  'Larger menus can take longer. You can cancel and retry with fewer photos.':'较大的菜单可能需要更长时间。你可以取消并减少照片数量后重试。',
  Back:'返回', 'Return to previous screen':'返回上一页',
  'Unlock YOEO Pro':'解锁 YOEO Pro',
  'Save results and revisit them anytime with YOEO Pro.':'使用 YOEO Pro 保存结果，随时查看。',
  'You’ve used your three free scans. Get YOEO Pro to keep analyzing.':'三次免费扫描已用完。升级 YOEO Pro 继续分析。',
  'Unlimited analyses and saved results, all in one plan.':'一个方案，享受无限分析和结果保存。',
  'Sign up or sign in to upgrade':'注册或登录以升级',
  'Checking subscription…':'正在检查订阅…',

  'Eat safely everyday':'安心享用每一餐','Get started':'开始使用','What are you allergic to?':'你对什么过敏？','Choose the severity for each category':'为每个类别选择严重程度','Previous category':'上一个类别','Category {current} of {total}':'第 {current} 类，共 {total} 类','Not selected yet':'尚未选择',
  Critical:'严重',Avoid:'避免',Safe:'安全',Uncertain:'不确定',Untracked:'未跟踪',Next:'下一步','What’s your name?':'你叫什么名字？','Almost there — just one last step':'快完成了，只剩最后一步','Your name':'你的名字','Let’s go':'开始吧','Welcome to YOEO!':'欢迎使用 YOEO！','Get ready to eat safely everyday':'准备好安心享用每一餐','Continue to home':'前往首页','Hi {name},':'你好，{name}！','Ready to eat safely?':'准备好安心用餐了吗？','My Allergens':'我的过敏原',
  'Edit allergens':'编辑过敏原','Export allergen profile':'导出过敏档案','No allergens marked to avoid.':'没有标记需要避免的过敏原。','Review your allergen profile':'查看过敏档案','Start Analyzing':'开始分析','Add allergen':'添加过敏原','No allergens in {severity}.':'“{severity}”中没有过敏原。','Add an allergen to personalize your checks.':'添加过敏原以个性化检查。','“Safe” records your own tolerance. It does not verify that a dish is safe to eat.':'“安全”仅记录你的个人耐受情况，并不代表菜品已确认安全。',
  Home:'首页',Allergens:'过敏原',Profile:'个人资料','Main navigation':'主导航','Saved Results':'已保存结果',Subscription:'订阅','Edit Profile':'编辑个人资料','Data Sources':'数据来源','Data Resources':'数据来源','App Settings':'应用设置','Manage your preferences and local data.':'管理偏好设置和本地数据。','Sign in or create account':'登录或创建账户','Install YOEO on this phone':'在此手机上安装 YOEO','Sign out':'退出登录',Local:'本地',Free:'免费',Pro:'专业版','Pro scans active':'专业版扫描已启用','{remaining} of 3 free scans remaining':'3 次免费扫描还剩 {remaining} 次','{count} saved analysis on this device':'此设备已保存 {count} 次分析','{count} saved analyses on this device':'此设备已保存 {count} 次分析',
  Language:'语言','System default':'跟随系统',English:'英语',German:'德语','Simplified Chinese':'简体中文','Install on your phone':'安装到手机','Open your browser’s menu and choose “Add to Home Screen” or “Install app.”':'打开浏览器菜单，选择“添加到主屏幕”或“安装应用”。','Your data':'你的数据','Export my data':'导出我的数据',
  'Does this menu have an allergen list?':'这份菜单有过敏原列表吗？','Usually on the last page, marked with letter codes':'通常位于最后一页，并使用字母代码标记','Yes, upload the list':'是，上传列表','No, upload the menu':'否，上传菜单','Yes, take the list':'是，拍摄列表','No, take the menu':'否，拍摄菜单','Take the allergen list':'拍摄过敏原列表','Take the menu':'拍摄菜单','Review the allergen list':'检查过敏原列表','Review the menu':'检查菜单','Fit the {kind} inside the frame':'将{kind}放入取景框',menu:'菜单','allergen list':'过敏原列表','Choose a photo':'选择照片','Take photo':'拍照','Open device camera':'打开设备相机',Gallery:'相册','Device camera':'设备相机',Device:'设备',camera:'相机','Add a menu photo':'添加菜单照片','Allergen list':'过敏原列表',Menu:'菜单',Food:'食物',Add:'添加',photo:'照片','Continue to the menu':'继续拍摄菜单',
  'I agree to send these photos and my allergen preferences to YOEO’s server and {provider} for this analysis. AI can make mistakes; confirm ingredients and cross-contact with staff.':'我同意将这些照片和过敏原偏好发送至 YOEO 服务器及 {provider} 进行分析。AI 可能出错，请向工作人员确认配料和交叉接触风险。','Analysis needs your attention':'分析需要处理','Upgrade to Pro':'升级专业版','Sign in to continue':'登录后继续','Preparing photos…':'正在准备照片…','Analyze {count} photo':'分析 {count} 张照片','Analyze {count} photos':'分析 {count} 张照片','Retake this photo':'重新拍摄','Analyzing your results':'正在分析结果','Analyzing your results…':'正在分析结果…','Reading the menu and checking your allergens.':'正在读取菜单并检查你的过敏原。',Cancel:'取消','Discard this scan?':'放弃此次扫描？','Your photos won’t be saved.':'你的照片不会被保存。',Discard:'放弃',Continue:'继续',
  Milk:'牛奶',Eggs:'鸡蛋','Cereals containing gluten':'含麸质谷物','Peanuts & Tree Nuts':'花生与坚果','Fish, Crustaceans & Molluscs':'鱼类、甲壳类与软体动物','Soybeans, Lupin & Sesame':'大豆、羽扇豆与芝麻','Celery & Mustard':'芹菜与芥末',Sulphites:'亚硫酸盐',
  All:'全部','Allergen Check':'过敏原检查','Select what to show':'选择显示内容','Show all results':'显示全部结果','Check all {count} dishes at once':'一次检查全部 {count} 道菜','Or select specific dishes':'或选择特定菜品','Check {count} dishes':'检查 {count} 道菜','Allergens found':'发现的过敏原','No allergens were identified. Safety is still unconfirmed.':'未识别出过敏原，安全性仍未确认。','From allergen list':'来自过敏原列表','Declared on menu':'菜单中已标明','AI estimate':'AI 估计','No allergens identified':'未识别出过敏原','Safety is unconfirmed':'安全性未确认','Evidence & questions':'依据与问题','Visible / listed ingredients:':'可见／列出的配料：',Declared:'已标明',Possible:'可能含有','What we couldn’t confirm':'无法确认的内容','Ask the restaurant':'询问餐厅','No dishes in this category.':'此类别中没有菜品。','Confirm before you eat':'食用前请确认','Read the allergen list':'查看过敏原列表','Read the menu':'查看菜单','No additional menu text was extracted.':'未提取到其他菜单文字。','Download structured report (JSON)':'下载结构化报告（JSON）','Analysis from {date}. Based on your allergen profile at that time.':'分析时间：{date}。依据当时的过敏原档案。','Results saved on this device':'结果已保存到此设备','Save results':'保存结果','Back to home':'返回首页','Filter saved results':'筛选已保存结果','Delete {title}':'删除 {title}','No tracked allergens detected':'未检测到已跟踪的过敏原','Confirm ingredients before eating':'食用前请确认配料','No matching results':'没有匹配结果','Your results, in one place':'集中查看你的结果','Choose another filter to see your saved analyses.':'选择其他筛选条件以查看已保存的分析。','Save an analysis to come back to it here.':'保存分析后即可在此再次查看。','Analyze a menu':'分析菜单','Go back':'返回','Close':'关闭','Profile photo':'个人头像','Open profile':'打开个人资料',
  'View and change profile photo':'查看并更换头像','Profile saved':'个人资料已保存',Name:'姓名','Email address':'电子邮箱','Sign in to connect your email':'登录以关联邮箱','Reset password':'重置密码',Save:'保存','Delete account':'删除账户','Delete local profile and results':'删除本地档案和结果','Clear local data':'清除本地数据','Delete data':'删除数据','Delete data?':'删除数据？','Deleting…':'正在删除…','Deleting your data…':'正在删除你的数据…','Deleting your account and associated data. This usually takes a few seconds.':'正在删除你的账户和关联数据，通常只需几秒钟。','Removing your data from this device. This usually takes a few seconds.':'正在从此设备移除你的数据，通常只需几秒钟。','Your data has been deleted':'你的数据已删除','Your account, associated database data, and all data stored by this app on this device have been deleted.':'你的账户、关联数据库数据以及此应用存储在本设备上的所有数据均已删除。','All data stored by this app on this device has been deleted.':'此应用存储在本设备上的所有数据均已删除。','Keep my data':'保留我的数据','Close profile photo':'关闭头像','Choose image source':'选择图片来源',Camera:'相机',Photo:'照片','Close allergen details':'关闭过敏原详情','Move to {severity}':'移至“{severity}”','Remove from profile':'从档案中移除',Allergen:'过敏原',Severity:'严重程度','Save allergen':'保存过敏原',
};

const dictionaries: Record<AppLanguage, Record<string, string>> = { en: {}, de, 'zh-CN': zh };
const normalize = (value: string): AppLanguage => value.toLowerCase().startsWith('de') ? 'de' : value.toLowerCase().startsWith('zh') ? 'zh-CN' : 'en';
const detectSystemLanguage = () => normalize(navigator.languages?.[0] || navigator.language || 'en');
const interpolate = (text: string, values?: Record<string, string | number>) => Object.entries(values || {}).reduce((result,[key,value]) => result.replaceAll(`{${key}}`,String(value)),text);
type I18nValue = { language: AppLanguage; preference: LanguagePreference; setPreference:(value:LanguagePreference)=>void; t:(key:string, values?:Record<string,string|number>)=>string };
const I18nContext = createContext<I18nValue | null>(null);

export function I18nProvider({children}:{children:ReactNode}) {
  const stored = (localStorage.getItem(STORAGE_KEY) || 'system') as LanguagePreference;
  const [preference,setPreferenceState] = useState<LanguagePreference>(['system','en','de','zh-CN'].includes(stored) ? stored : 'system');
  const [system,setSystem] = useState(detectSystemLanguage);
  const language = preference === 'system' ? system : preference;
  useEffect(()=>{const update=()=>setSystem(detectSystemLanguage());window.addEventListener('languagechange',update);return()=>window.removeEventListener('languagechange',update);},[]);
  useEffect(()=>{document.documentElement.lang=language;},[language]);
  const value=useMemo<I18nValue>(()=>({language,preference,setPreference:(next)=>{setPreferenceState(next);localStorage.setItem(STORAGE_KEY,next);},t:(key,values)=>interpolate(dictionaries[language][key]||key,values)}),[language,preference]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}
export function useI18n(){const value=useContext(I18nContext);if(!value)throw Error('useI18n must be used inside I18nProvider');return value;}
